import pyray as pr

APP_NAME = "Tutorial1 - Space Race"

WINDOW_WIDTH = 512  # px
WINDOW_HEIGHT = 512  # px
FRAME_RATE = 60  # fps

ACTION_KEYPRESS = "keypress"
ACTION_TIMEOUT = "timeout"
ACTION_NONE = "none"

GAME_TIMEOUT = 45.0  # seconds
GAME_OVER_TIMEOUT = 10 # seconds

PLAYER1_RAIL = WINDOW_WIDTH * 1 // 3
PLAYER1_CONTROLS = (pr.KeyboardKey.KEY_Q, pr.KeyboardKey.KEY_A)
PLAYER2_RAIL = WINDOW_WIDTH * 2 // 3
PLAYER2_CONTROLS = (pr.KeyboardKey.KEY_UP, pr.KeyboardKey.KEY_DOWN)

PLAYER_MASS = 16
PLAYER_SPEED = 100
PLAYERS_START = WINDOW_HEIGHT * 9 // 10

ASTEROID_COUNT = 40
ASTEROID_MASS = 8
ASTEROID_SPEED = 50
ASTEROIDS_START_ZONE = WINDOW_HEIGHT * 1 // 10
ASTEROIDS_END_ZONE = WINDOW_HEIGHT * 8 // 10
