import pyray as pr

APP_NAME = "Tutorial1 - Space Race"

WINDOW_WIDTH = 512  # px
WINDOW_HEIGHT = 512  # px
FRAME_RATE = 60  # fps

ACTION_KEYPRESS = "keypress"
ACTION_TIMEOUT = "timeout"
ACTION_NONE = "none"

GAME_TIMEOUT = 45.0  # s
GAME_OVER_TIMEOUT = 10  # s

PLAYER1_RAIL = WINDOW_WIDTH * 1 // 3  # px
PLAYER1_CONTROLS = (pr.KeyboardKey.KEY_Q, pr.KeyboardKey.KEY_A)
PLAYER2_RAIL = WINDOW_WIDTH * 2 // 3  # px
PLAYER2_CONTROLS = (pr.KeyboardKey.KEY_UP, pr.KeyboardKey.KEY_DOWN)

START_CONTROL = pr.KeyboardKey.KEY_SPACE

PLAYER_MASS = 16  # t
PLAYER_SPEED = 100  # px.s-1
PLAYERS_START = WINDOW_HEIGHT * 9 // 10  # px

ASTEROID_COUNT = 40
ASTEROID_MASS = 8  # t
ASTEROID_SPEED = 50  # px.s-1
ASTEROIDS_START_ZONE = WINDOW_HEIGHT * 1 // 10  # px
ASTEROIDS_END_ZONE = WINDOW_HEIGHT * 8 // 10  # px

AUDIO_MAX_SAMPLES_PER_UPDATE = 4096
AUDIO_SAMPLE_RATE = 44100  # Hz
AUDIO_VOLUME = 0.1  # %
AUDIO_FREQ_START = 440  # Hz
AUDIO_FREQ_STOP = 880  # Hz
