from typing import Any, Protocol

from tinyrpg.engine.game.character import Character


class Quest(Protocol):
    def reset(self): ...

    def is_assignable(self, character: Character) -> bool: ...

    def is_completed(self) -> bool: ...

    def process_next_state(self, game): ...

    def save_state(self) -> dict[str, Any]: ...

    def restore_state(self, state: dict[str, Any]): ...
