"""Render engine protocol abstraction."""

from typing import Protocol
from greensquare.core.state import PlayerState


class RenderEngine(Protocol):
    """Abstract rendering engine protocol."""

    def init_window(self) -> None: ...

    def close_window(self) -> None: ...

    def window_should_close(self) -> bool: ...

    def get_frame_time(self) -> float: ...

    def begin_frame(self) -> None: ...

    def render_game(self, player: PlayerState) -> None: ...

    def end_frame(self) -> None: ...
