APP_NAME = "Tutorial5 - TinyRpg"

WINDOW_WIDTH = 1024  # px
WINDOW_HEIGHT = 1024  # px
FRAME_RATE = 60  # fps

DEBUG_ENABLED = False

CAMERA_SPEED = 5  # px.s-1

WORLD_WIDTH = 256  # px
WORLD_HEIGHT = 256  # px
WORLD_LAYER_COUNT = 3
WORLD_BACKGROUND_LAYER = 0
WORLD_FOREGROUND_LAYER = 1
WORLD_DEBUG_LAYER = 2

ENTITY_MASS_DEFAULT = 1.0  # kg
ENTITY_DENSITY_DEFAULT = 8  # px.kg-1

CHARACTER_TRIGGER_NEAR_DEFAULT = 16  # px
CHARACTER_TRIGGER_FAR_DEFAULT = 64  # px
CHARACTER_FREE_TIMER = 60  # s

INPUT_GOTO_MENU = "HOME"
INPUT_ATTACK = "SQUARE"
INPUT_OPEN_INVENTORY = "TRIANGLE"
INPUT_INVENTORY_NEXT = "RIGHT"
INPUT_INVENTORY_PREVIOUS = "LEFT"
INPUT_INVENTORY_CLOSE = "CIRCLE"
INPUT_INVENTORY_EQUIP = "CROSS"
INPUT_INVENTORY_UNEQUIP = "CROSS"
INPUT_INVENTORY_DROP = "TRIANGLE"
INPUT_SHOPPING_CART_NEXT = "RIGHT"
INPUT_SHOPPING_CART_PREVIOUS = "LEFT"
INPUT_SHOPPING_CART_CLOSE = "CIRCLE"
INPUT_SHOPPING_CART_BUY = "CROSS"
INPUT_SHOPPING_CART_SELL = "CROSS"
INPUT_MESSAGE_NEXT = "CROSS"
INPUT_MENU_BOX_NEXT = "DOWN"
INPUT_MENU_BOX_PREVIOUS = "UP"
INPUT_MENU_BOX_SELECT = "CROSS"

MAX_AVOID_FORCE = 2000  # N

EPSILON = 1e-6

DIR4 = [
    (0, -1),
    (1, 0),
    (0, 1),
    (-1, 0),
]

DIR8 = [
    (0, -1),
    (1, -1),
    (1, 0),
    (1, 1),
    (0, 1),
    (-1, 1),
    (-1, 0),
    (-1, -1),
]
