default:
  just --list

sync:
  uv sync

update:
  uv lock --upgrade
  uv sync

clean:
  uvx pyclean .
  rm -rf dist

format:
  uvx ruff format --extend-select "I"

check:
  uvx ruff check
  uvx ty check

test TEST:
  uv run pytest {{TEST}}

test-all:
  uv run pytest

build: check
  uv build

publish:
  uv publish

run:
  uv run tinyrpg
