"""
Immutable world constants.
"""

GRID_SIZE = 20  # Playable grid size GRID_SIZE x GRID_SIZE
GRID_CELL_SIZE = 32

# Borders (in cells)
BORDER_LEFT = 1
BORDER_RIGHT = 1
BORDER_TOP = 4
BORDER_BOTTOM = 1

# Total Screen Size
SCREEN_WIDTH = (GRID_SIZE + BORDER_LEFT + BORDER_RIGHT) * GRID_CELL_SIZE
SCREEN_HEIGHT = (GRID_SIZE + BORDER_TOP + BORDER_BOTTOM) * GRID_CELL_SIZE

# Grid Start Offsets
GRID_OFFSET_X = BORDER_LEFT * GRID_CELL_SIZE
GRID_OFFSET_Y = BORDER_TOP * GRID_CELL_SIZE

TARGET_RECT_SIZE = 3
WINDOW_TITLE = "Grid Physics Ball"
EPSILON = 0.00001
