default:
	just --list

sync:
	uv sync

update:
	uv lock --upgrade
	uv sync

clean:
	uvx pyclean .
	rm -rf dist

test TEST:
	uvx pytest {{TEST}}

test-all:
	uvx pytest

build:
	uv build

publish:
	uv publish

run:
	uv run marchingsquare
